### ISSUE TITLE
Licence for Training Data

### ISSUE THREAD

**Issue by ONE-RANDOM-HUMAN** [official-stockfish/nnue-pytorch#229]
I would like to use the training data linked in the wiki for training my own (unrelated to Stockfish) networks. However, the wiki doesn't seem to make any mention of the license for the data, nor does there seem to be any obvious place to find it.

Please add this information to the wiki if possible.

**Comment by Sopel97** [comment]
It's still unclear if the training data Stockfish uses is even copyrightable in the first place. Either way the choice of the license falls under whoever distributes it, and therefore we cannot do anything about it from the perspective of the links in the wiki.
