### ISSUE TITLE
Error with visualize.py

### ISSUE THREAD

**Issue by benliu961** [official-stockfish/nnue-pytorch#241]
Hello,

I am getting an error of AttributeError: 'FeatureSet' object has no attribute 'num_ls_buckets' when I try to run visualize.py

What am I doing incorrectly and how can I fix it?

Thank you!

**Comment by Sopel97** [comment]
the script might be out of date and need some changes, wasn't used in a long time

**Comment by Sopel97** [comment]
https://github.com/official-stockfish/nnue-pytorch/issues/188
