### ISSUE TITLE
Easy Train problems w/ Ubuntu 24 (python 3.12)

### ISSUE THREAD

**Issue by protonspring** [official-stockfish/nnue-pytorch#286]
First, after "python3 -m venv trainer", the environment is created, but not started automatically.  Thus, I have to run "source trainer/bin/activate" to start it.

Then, when I run "pip install -r requirements" I get:  

ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu118 (from versions: 2.2.0, 2.2.0+cpu, 2.2.0+cpu.cxx11.abi, 2.2.0+cu118, 2.2.0+cu121, 2.2.0+rocm5.6, 2.2.0+rocm5.7, 2.2.1, 2.2.1+cpu, 2.2.1+cpu.cxx11.abi, 2.2.1+cu118, 2.2.1+cu121, 2.2.1+rocm5.6, 2.2.1+rocm5.7, 2.2.2, 2.2.2+cpu, 2.2.2+cpu.cxx11.abi, 2.2.2+cu118, 2.2.2+cu121, 2.2.2+rocm5.6, 2.2.2+rocm5.7, 2.3.0, 2.3.0+cpu, 2.3.0+cpu.cxx11.abi, 2.3.0+cu118, 2.3.0+cu121, 2.3.0+rocm5.7, 2.3.0+rocm6.0, 2.3.1, 2.3.1+cpu, 2.3.1+cpu.cxx11.abi, 2.3.1+cu118, 2.3.1+cu121, 2.3.1+rocm5.7, 2.3.1+rocm6.0, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==2.0.1+cu118

I can change 2.0.1+cu118 to 2.2.0+cu118 and things seem to install correctly, but I inevitably have python issues. . starting with:

A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with pybind11>=2.12'.

Also, when running the easy_train.sh. . . I get "ModuleNotFoundError: No module named 'requests'"  This is solved by pip install requests.

Ultimately. . I think the main issue is here: "/store/dev/chess/nnue-pytorch/nnue-pytorch/trainer/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)"

So, I don't know how to proceed from there.  The trainer GUI comes up, but immediately says "Run 0 - Exited unexpectedly." and "Error: Unknown error occured."

**Comment by protonspring** [comment]
When I run "pip install -r requirements.txt", numpy-2.0.2 is installed.

**Comment by Sopel97** [comment]
try python 3.11

**Comment by protonspring** [comment]
Thanks for the help.  Python3.11 installs fine, however, when I do "python3.11 -m venv trainer" I get:

Error: Command '['/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/trainer/bin/python3.11', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

The problem is apparently "ensurepip" is not a supported option for python3.11.

**Comment by Sopel97** [comment]
you don't have venv installed for python 3.11

**Comment by protonspring** [comment]
ok, apt install python3.11-venv, worked and all of the requirements.txt stuff installed fine.  Crossing finger. . .

**Comment by protonspring** [comment]
When I run a version of easy_train_example.sh, the trainer still says "Exited Unexpectedly."

When I run the command in the background manually, I get:

No .nnue files found in /home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/training

Do I need to make a network somehow before training?

**Comment by protonspring** [comment]
Here is the output from running the script. . . nothing looks abnormal to me:

Found python version 3.11.10 (main, Sep  7 2024, 18:35:41) [GCC 13.2.0]. OK.
Found make executable version 4.3. OK.
Found cmake executable version 3.30.3. OK.
Found gcc executable version 13.2.0. OK.
Found asciimatics package. OK.
Found torch version 2.0.1+cu118. OK.
Found torch with CUDA. OK.
Found pytorch_lightning version 1.9.5. OK.
Found cupy version None. OK.
Found GPUtil version 1.4.0. OK.
Initializing...
c-chess-cli already setup in /home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/c-chess-cli
Engines provided. Enabling network testing.
Stockfish already setup in /home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/stockfish_base.
Stockfish already setup in /home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/stockfish_test.
nnue-pytorch already setup in /home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/nnue-pytorch
Initialization completed.
Doing network training on gpus [0]. 2 runs in total.
Running training with command: ['/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/trainer/bin/python', 'train.py', '--num-workers=4', '--threads=2', '--max_epoch=10', '--batch-size=16384', '--random-fen-skipping=3', '--early-fen-skipping=-1', '--gpus=0,', '--features=HalfKAv2_hm^', '--lr=0.000875', '--gamma=0.992', '--lambda=1.0', '--network-save-period=1', '--save-last-network=True', '--seed=43', '--epoch-size=1638400', '--validation-size=16384', '--default_root_dir=/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/training/run_1', '--smart-fen-skipping', '--start-lambda=1.0', '--end-lambda=0.75', '--detect_anomaly=False', '/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/nodes5000pv2_UHO.binpack', '--validation-data=/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/nodes5000pv2_UHO.binpack']
Running network testing with command: ['/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/trainer/bin/python', 'run_games.py', '/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/training', '--concurrency=24', '--explore_factor=1.5', '--c_chess_exe=/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/c-chess-cli/c-chess-cli', '--stockfish_base=/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/stockfish_base/src/stockfish', '--stockfish_test=/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/stockfish_test/src/stockfish', '--book_file_name=/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/UHO_4060_v3.epd.zip', '--hash=8', '--games_per_round=200', '--features=HalfKAv2_hm^', '--nodes_per_move=20000']

**Comment by protonspring** [comment]
Sorry.. . . that was the testing command. . . when I run the training command in the background, I get the same numpy API above:

A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with pybind11>=2.12'.

/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/trainer/lib/python3.11/site-packages/pytorch_lightning/overrides/data_parallel.py:119: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)

**Comment by Sopel97** [comment]
> When I run a version of easy_train_example.sh, the trainer still says "Exited Unexpectedly." (for GPU side)

You need to check the logs if there's something more. They should be in the experiment's dir.

> No .nnue files found in /home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/easy_train_data/experiments/experiment_test/training (and just repeats every 5 sec or so).

That's expected. The easy train script has two parts - training and testing. The testing is waiting for the trainer to produce a network.

> Do I need to make a network somehow before training?

no

> Sorry.. . . that was the testing command. . . when I run the training command in the background

I don't understand. They are not separate commands. It's one command that does both. You can even see it in the output that it spawns both the testing and training processes.

-----------------------------------------

I can't advise on the numpy issue, something is wrong with your python setup. Maybe some wrong dependency is getting installed. I suggest installing latest pytorch with cuda yourself (i.e. not from requirements txt), and trying to downgrade numpy to 1.*.

**Comment by protonspring** [comment]
Great. . thank you.  I'll try those things.

**Comment by Sopel97** [comment]
I see that pytorch may now support numpy 2, but I'm unsure since what version https://github.com/pytorch/pytorch/issues/107302

**Comment by protonspring** [comment]
ok. .progress. . . when I use python 3.10, and add "numpy==1.26.4" and "requests" to requirements.txt, everything seems to setup with no errors.

When I run the easy trainer, the GPU side still says "Unexpected error. . . " or "exited unexpectedly," and nothing happens. . . however, when I run the command manually it starts running epochs.

Not sure what the difference is yet. . .

**Comment by protonspring** [comment]
There are some deprecation output that maybe is messing up the trainer gui.

**Comment by protonspring** [comment]
The only thing I can find is:

Exception in thread Thread-3 (run_match):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikew/dev/chess/nnue-pytorch/nnue-pytorch/run_games.py", line 140, in run_match
    line = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 21: invalid start byte
Found 3 nn-epoch*.nnue files

**Comment by protonspring** [comment]
So, I can do some training if I run the commands manually, but the trainer gui doesn't appear to do anything.

**Comment by protonspring** [comment]
The hard way is working (it seems). . . but I'm getting 1.50it/sec.  That seems pretty darn slow.  Using nvidia-smi it appears is though the GPU is being used. . . does this speed seem reasonable for a GTX 1660 Ti ?

**Comment by Sopel97** [comment]
I don't think your GPU has enough VRAM, and it's definitely not fast enough for training.

**Comment by protonspring** [comment]
Thank you.  I'll close this issue.

**Comment by protonspring** [comment]
Sry. . . last question. . I have a heavier desktop with a RTX3070ti (6k cuda cores) . . still, I only get 8it/sec. . . does that seem normal?  I expected much higher rates than that.

**Comment by Sopel97** [comment]
that sounds about normal

I haven't trained with the newest arch, but generally even an A100 needs a few days for one training session
